### ISSUE TITLE
[CLOSED] When an non existent predicate is given in the .data file an exception is thrown instead of error reporting

### ISSUE THREAD

**Issue by eriq-augustine** [linqs/psl#218]
<a href="https://github.com/vasiloglou"><img src="https://avatars2.githubusercontent.com/u/1102516?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vasiloglou](https://github.com/vasiloglou)**
_Tuesday Aug 21, 2018 at 03:05 GMT_
_Originally opened as https://github.com/eriq-augustine/psl/issues/171_

----

if in the .data file I specify a predicate under targets that is nonexistent I get a java exception 

Unexpected exception!

java.lang.IllegalArgumentException: Unknown predicate specified: null

	at org.linqs.psl.database.rdbms.RDBMSDataStore.getInserter(RDBMSDataStore.java:216)

	at org.linqs.psl.cli.DataLoader.loadData(DataLoader.java:121)

	at org.linqs.psl.cli.DataLoader.loadPartitions(DataLoader.java:98)

	at org.linqs.psl.cli.DataLoader.load(DataLoader.java:77)

	at org.linqs.psl.cli.Launcher.loadData(Launcher.java:233)

	at org.linqs.psl.cli.Launcher.run(Launcher.java:386)

	at org.linqs.psl.cli.Launcher.main(Launcher.java:660)

	at org.linqs.psl.cli.Launcher.main(Launcher.java:649)

ERROR: Failed to run inference

I would be better if you do a check and report it as an error. It would be easier for the users to figure out what is going wrong.

**Comment by eriq-augustine** [comment]
<a href="https://github.com/eriq-augustine"><img src="https://avatars0.githubusercontent.com/u/337857?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [eriq-augustine](https://github.com/eriq-augustine)**
_Wednesday Aug 22, 2018 at 06:30 GMT_

----

Complete in ac2f9a30d42951a4c0c9a90ade1edfdce0e2fe5d.
