### ISSUE TITLE
mvn install -P Gurobi 

### ISSUE THREAD

**Issue by AlexFanC** [linqs/psl#345]
Skipping Postgres test... cannot connect to database.
162494 [main] ERROR com.zaxxer.hikari.pool.HikariPool  - HikariPool-343 - Exception during pool initialization.
org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:319) ~[postgresql-42.4.3.jar:42.4.3]
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49) ~[postgresql-42.4.3.jar:42.4.3]
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:247) ~[postgresql-42.4.3.jar:42.4.3]
        at org.postgresql.Driver.makeConnection(Driver.java:434) ~[postgresql-42.4.3.jar:42.4.3]
        at org.postgresql.Driver.connect(Driver.java:291) ~[postgresql-42.4.3.jar:42.4.3]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121) ~[HikariCP-4.0.3.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-4.0.3.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-4.0.3.jar:?]
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[HikariCP-4.0.3.jar:?]
        at org.linqs.psl.database.rdbms.driver.DatabaseDriver.<init>(DatabaseDriver.java:59) ~[classes/:?]
        at org.linqs.psl.database.rdbms.driver.PostgreSQLDriver.<init>(PostgreSQLDriver.java:68) ~[classes/:?]
        at org.linqs.psl.database.rdbms.driver.PostgreSQLDriver.<init>(PostgreSQLDriver.java:64) ~[classes/:?]
        at org.linqs.psl.database.rdbms.driver.PostgreSQLDriver.<init>(PostgreSQLDriver.java:58) ~[classes/:?]
        at org.linqs.psl.database.rdbms.driver.PostgreSQLDriver.<init>(PostgreSQLDriver.java:54) ~[classes/:?]
        at org.linqs.psl.database.DatabaseTestUtil.getPostgresDriver(DatabaseTestUtil.java:72) ~[test-classes/:?]
        at org.linqs.psl.database.rdbms.PostgresDataStoreTest.getDataStore(PostgresDataStoreTest.java:27) ~[test-classes/:?]
        at org.linqs.psl.database.DataStoreTest.getDataStore(DataStoreTest.java:94) ~[test-classes/:?]
        at org.linqs.psl.database.DataStoreTest.setUp(DataStoreTest.java:105) ~[test-classes/:?]
        at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) ~[junit-4.13.1.jar:4.13.1]
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) ~[junit-4.13.1.jar:4.13.1]
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) ~[junit-4.13.1.jar:4.13.1]
        at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33) ~[junit-4.13.1.jar:4.13.1]
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24) ~[junit-4.13.1.jar:4.13.1]
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) ~[junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) ~[junit-4.13.1.jar:4.13.1]
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) ~[junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) ~[junit-4.13.1.jar:4.13.1]
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) ~[junit-4.13.1.jar:4.13.1]
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) ~[junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) ~[junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) ~[junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) ~[junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) ~[junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) ~[junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) ~[junit-4.13.1.jar:4.13.1]
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413) ~[junit-4.13.1.jar:4.13.1]
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:344) ~[surefire-junit4-2.19.jar:2.19]
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:269) ~[surefire-junit4-2.19.jar:2.19]
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:240) ~[surefire-junit4-2.19.jar:2.19]
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:184) ~[surefire-junit4-2.19.jar:2.19]
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:286) ~[surefire-booter-2.19.jar:2.19]
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:240) ~[surefire-booter-2.19.ja

**Comment by cfpryor** [comment]
It looks like your PostgreSQL database might not be set up correctly. If you need help with installation, we have a guide here: [PostgreSQL setup guide](https://psl.linqs.org/wiki/Using-PostgreSQL-with-PSL.html).

If you’re not planning to use PostgreSQL, you can skip the tests during installation by running:

`mvn clean install -Dmaven.test.skip=true`

However if you intend to run any experiments that rely on PostgreSQL, you will need to have it installed.

I'll close for now, but go ahead and respond if you need more help or it doesn't work.

**Comment by AlexFanC** [comment]
Thank you for your answer. It succeeded
