### ISSUE TITLE
No signature of method: static org.linqs.psl.model.predicate.StandardPredicate.get()

### ISSUE THREAD

**Issue by th0o0** [linqs/psl#42]
I use the three jar `psl-groovy-CANARY.jar` `psl-dataloading-1.0.0.jar` `psl-cli-CANARY.jar` for my application, but I get the error as follows:

`Exception in thread "main" groovy.lang.MissingMethodException: No signature of method: static org.linqs.psl.model.predicate.StandardPredicate.get() is applicable for argument types: (java.lang.String, [Lorg.linqs.psl.model.term.ConstantType;) values: [Name, [UniqueIntID, UniqueStringID]]
Possible solutions: grep(), getAt(java.lang.String), wait(), any(), grep(java.lang.Object), getName()
	at groovy.lang.MetaClassImpl.invokeStaticMissingMethod(MetaClassImpl.java:1503)
	at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1489)
	at org.codehaus.groovy.runtime.callsite.StaticMetaClassSite.call(StaticMetaClassSite.java:53)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at org.linqs.psl.groovy.PSLModel.addPredicate(PSLModel.groovy:180)
	at org.linqs.psl.groovy.PSLModel.this$3$addPredicate(PSLModel.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:174)
	at org.linqs.psl.groovy.PSLModel.add(PSLModel.groovy:143)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
	at org.linqs.psl.examples.kgi.Run.definePredicates(Run.groovy:96)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
	at org.linqs.psl.examples.kgi.Run.run(Run.groovy:448)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
	at org.linqs.psl.examples.kgi.Run.main(Run.groovy:467)
`

- I guess my `predicate` have problem, but I can't make sure, here is my `code`:

public Run() {
    config = ConfigManager.getManager().getBundle("kgi")
    config.addProperty("admmreasoner.maxiterations", 125000)
    String suffix = System.getProperty("user.name") + "@" + getHostname()
    String baseDBPath = config.getString("dbpath", System.getProperty("java.io.tmpdir"))
    String dbPath = Paths.get(baseDBPath, this.getClass().getName() + "_" + suffix).toString()
    dataStore = new RDBMSDataStore(new H2DatabaseDriver(Type.Disk, dbPath, true), config)
    model = new PSLModel(this, dataStore)
	}
private void definePredicates() {
    model.add predicate: "Name", types: [ConstantType.UniqueIntID, ConstantType.UniqueStringID]
     }

**Comment by eriq-augustine** [comment]
The code you are showing there cannot be compatible with the current `CANARY`.
Both `ConfigManager` and `psl-dataloading` have not existed for a while.
They existed in `2.0.0`, but not in a canary since `CANARY-2.1.1` (the latest canary is `CANARY-2.1.6`).

We just did a new release of PSL, why don't you use that version (`2.1.0`)?
If you are determined to use a canary, please make sure to read this: https://github.com/linqs/psl/wiki/Working-With-Canary

Since it seems you have maven issues (with getting it to download versions from behind your proxy), why not use the CLI?
https://github.com/linqs/psl/wiki/Using-the-CLI
You only have to download one jar file (and the `run.sh` scripts in the psl-examples automatically download it for you).

**Comment by th0o0** [comment]
I use the `psl-groovy-CANARY-2.1.0.jar` `psl-cli-CANARY.jar` `psl-dataloading-CANARY-2.1.0` solve the problem.

Appreciate your help.
